<map id="django.contrib.gis.utils.layermapping.LayerMapError" name="django.contrib.gis.utils.layermapping.LayerMapError">
<area shape="rect" id="Node000001" title=" " alt="" coords="140,101,408,141"/>
<area shape="rect" id="Node000003" href="$classdjango_1_1contrib_1_1gis_1_1utils_1_1layermapping_1_1InvalidDecimal.html" title=" " alt="" coords="456,5,724,45"/>
<area shape="poly" id="edge2_Node000001_Node000003" title=" " alt="" coords="339,94,455,55,499,43,501,48,457,60,341,99"/>
<area shape="rect" id="Node000004" href="$classdjango_1_1contrib_1_1gis_1_1utils_1_1layermapping_1_1InvalidInteger.html" title=" " alt="" coords="456,69,724,109"/>
<area shape="poly" id="edge3_Node000001_Node000004" title=" " alt="" coords="421,104,455,100,456,106,422,109"/>
<area shape="rect" id="Node000005" href="$classdjango_1_1contrib_1_1gis_1_1utils_1_1layermapping_1_1InvalidString.html" title=" " alt="" coords="456,133,724,173"/>
<area shape="poly" id="edge4_Node000001_Node000005" title=" " alt="" coords="422,134,456,137,455,142,421,139"/>
<area shape="rect" id="Node000006" href="$classdjango_1_1contrib_1_1gis_1_1utils_1_1layermapping_1_1MissingForeignKey.html" title=" " alt="" coords="456,197,724,237"/>
<area shape="poly" id="edge5_Node000001_Node000006" title=" " alt="" coords="341,144,457,183,501,195,499,200,455,188,339,149"/>
<area shape="rect" id="Node000002" title=" " alt="" coords="5,109,92,134"/>
<area shape="poly" id="edge1_Node000001_Node000002" title=" " alt="" coords="106,119,140,119,140,124,106,124"/>
</map>
