\doxysection{Référence de la classe pandas.\+errors.\+Unsupported\+Function\+Call}
\hypertarget{classpandas_1_1errors_1_1UnsupportedFunctionCall}{}\label{classpandas_1_1errors_1_1UnsupportedFunctionCall}\index{pandas.errors.UnsupportedFunctionCall@{pandas.errors.UnsupportedFunctionCall}}


Graphe d\textquotesingle{}héritage de pandas.\+errors.\+Unsupported\+Function\+Call\+:
% FIG 0


Graphe de collaboration de pandas.\+errors.\+Unsupported\+Function\+Call\+:
% FIG 1


\doxysubsection{Description détaillée}
\begin{DoxyVerb}Exception raised when attempting to call a unsupported numpy function.

For example, ``np.cumsum(groupby_object)``.

Examples
--------
>>> df = pd.DataFrame({"A": [0, 0, 1, 1],
...                    "B": ["x", "x", "z", "y"],
...                    "C": [1, 2, 3, 4]}
...                   )
>>> np.cumsum(df.groupby(["A"]))
Traceback (most recent call last):
UnsupportedFunctionCall: numpy operations are not valid with groupby.
Use .groupby(...).cumsum() instead
\end{DoxyVerb}
 

La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/pandas/errors/\mbox{\hyperlink{env_2lib_2python3_812_2site-packages_2pandas_2errors_2____init_____8py}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}\end{DoxyCompactItemize}
