\doxysection{Référence de la classe pandas.\+errors.\+Numba\+Util\+Error}
\hypertarget{classpandas_1_1errors_1_1NumbaUtilError}{}\label{classpandas_1_1errors_1_1NumbaUtilError}\index{pandas.errors.NumbaUtilError@{pandas.errors.NumbaUtilError}}


Graphe d\textquotesingle{}héritage de pandas.\+errors.\+Numba\+Util\+Error\+:
% FIG 0


Graphe de collaboration de pandas.\+errors.\+Numba\+Util\+Error\+:
% FIG 1


\doxysubsection{Description détaillée}
\begin{DoxyVerb}Error raised for unsupported Numba engine routines.

Examples
--------
>>> df = pd.DataFrame({"key": ["a", "a", "b", "b"], "data": [1, 2, 3, 4]},
...                   columns=["key", "data"])
>>> def incorrect_function(x):
...     return sum(x) * 2.7
>>> df.groupby("key").agg(incorrect_function, engine="numba")
Traceback (most recent call last):
NumbaUtilError: The first 2 arguments to incorrect_function
must be ['values', 'index']
\end{DoxyVerb}
 

La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/pandas/errors/\mbox{\hyperlink{env_2lib_2python3_812_2site-packages_2pandas_2errors_2____init_____8py}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}\end{DoxyCompactItemize}
