\doxysection{Référence de la classe django.\+db.\+utils.\+Database\+Error\+Wrapper}
\hypertarget{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper}{}\label{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper}\index{django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}}
\doxysubsubsection*{Fonctions membres publiques}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_ac3c616230fb2ef105c1597aad2ef98f7}{\+\_\+\+\_\+init\+\_\+\+\_\+}} (self, \mbox{\hyperlink{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_a6e49a03de1f29b7f126c7c6223f6765e}{wrapper}})
\item 
\mbox{\hyperlink{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_adebc6646e642696f89e52dd5b0dafbc1}{\+\_\+\+\_\+enter\+\_\+\+\_\+}} (self)
\item 
\mbox{\hyperlink{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_a195f9979e4167d913b96667a3051c7c3}{\+\_\+\+\_\+exit\+\_\+\+\_\+}} (self, exc\+\_\+type, exc\+\_\+value, traceback)
\item 
\mbox{\hyperlink{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_ada4e6306ea2c76469edf4f7903b7c1db}{\+\_\+\+\_\+call\+\_\+\+\_\+}} (self, func)
\end{DoxyCompactItemize}
\doxysubsubsection*{Attributs publics}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_a6e49a03de1f29b7f126c7c6223f6765e}{wrapper}}
\end{DoxyCompactItemize}


\doxysubsection{Description détaillée}
\begin{DoxyVerb}Context manager and decorator that reraises backend-specific database
exceptions using Django's common wrappers.
\end{DoxyVerb}
 

\doxysubsection{Documentation des constructeurs et destructeur}
\Hypertarget{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_ac3c616230fb2ef105c1597aad2ef98f7}\label{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_ac3c616230fb2ef105c1597aad2ef98f7} 
\index{django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}!\_\_init\_\_@{\_\_init\_\_}}
\index{\_\_init\_\_@{\_\_init\_\_}!django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}}
\doxysubsubsection{\texorpdfstring{\_\_init\_\_()}{\_\_init\_\_()}}
{\footnotesize\ttfamily django.\+db.\+utils.\+Database\+Error\+Wrapper.\+\_\+\+\_\+init\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self,  }\item[{}]{wrapper }\end{DoxyParamCaption})}

\begin{DoxyVerb}wrapper is a database wrapper.

It must have a Database attribute defining PEP-249 exceptions.
\end{DoxyVerb}
 

\doxysubsection{Documentation des fonctions membres}
\Hypertarget{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_ada4e6306ea2c76469edf4f7903b7c1db}\label{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_ada4e6306ea2c76469edf4f7903b7c1db} 
\index{django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}!\_\_call\_\_@{\_\_call\_\_}}
\index{\_\_call\_\_@{\_\_call\_\_}!django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}}
\doxysubsubsection{\texorpdfstring{\_\_call\_\_()}{\_\_call\_\_()}}
{\footnotesize\ttfamily django.\+db.\+utils.\+Database\+Error\+Wrapper.\+\_\+\+\_\+call\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self,  }\item[{}]{func }\end{DoxyParamCaption})}

\Hypertarget{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_adebc6646e642696f89e52dd5b0dafbc1}\label{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_adebc6646e642696f89e52dd5b0dafbc1} 
\index{django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}!\_\_enter\_\_@{\_\_enter\_\_}}
\index{\_\_enter\_\_@{\_\_enter\_\_}!django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}}
\doxysubsubsection{\texorpdfstring{\_\_enter\_\_()}{\_\_enter\_\_()}}
{\footnotesize\ttfamily django.\+db.\+utils.\+Database\+Error\+Wrapper.\+\_\+\+\_\+enter\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self }\end{DoxyParamCaption})}

\Hypertarget{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_a195f9979e4167d913b96667a3051c7c3}\label{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_a195f9979e4167d913b96667a3051c7c3} 
\index{django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}!\_\_exit\_\_@{\_\_exit\_\_}}
\index{\_\_exit\_\_@{\_\_exit\_\_}!django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}}
\doxysubsubsection{\texorpdfstring{\_\_exit\_\_()}{\_\_exit\_\_()}}
{\footnotesize\ttfamily django.\+db.\+utils.\+Database\+Error\+Wrapper.\+\_\+\+\_\+exit\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self,  }\item[{}]{exc\+\_\+type,  }\item[{}]{exc\+\_\+value,  }\item[{}]{traceback }\end{DoxyParamCaption})}



\doxysubsection{Documentation des données membres}
\Hypertarget{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_a6e49a03de1f29b7f126c7c6223f6765e}\label{classdjango_1_1db_1_1utils_1_1DatabaseErrorWrapper_a6e49a03de1f29b7f126c7c6223f6765e} 
\index{django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}!wrapper@{wrapper}}
\index{wrapper@{wrapper}!django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}}
\doxysubsubsection{\texorpdfstring{wrapper}{wrapper}}
{\footnotesize\ttfamily django.\+db.\+utils.\+Database\+Error\+Wrapper.\+wrapper}



La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/django/db/\mbox{\hyperlink{django_2db_2utils_8py}{utils.\+py}}\end{DoxyCompactItemize}
