\doxysection{Référence de la classe django.\+contrib.\+gis.\+geoip2.\+Geo\+IP2\+Exception}
\hypertarget{classdjango_1_1contrib_1_1gis_1_1geoip2_1_1GeoIP2Exception}{}\label{classdjango_1_1contrib_1_1gis_1_1geoip2_1_1GeoIP2Exception}\index{django.contrib.gis.geoip2.GeoIP2Exception@{django.contrib.gis.geoip2.GeoIP2Exception}}


Graphe d\textquotesingle{}héritage de django.\+contrib.\+gis.\+geoip2.\+Geo\+IP2\+Exception\+:
% FIG 0


Graphe de collaboration de django.\+contrib.\+gis.\+geoip2.\+Geo\+IP2\+Exception\+:
% FIG 1


La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/django/contrib/gis/\mbox{\hyperlink{geoip2_8py}{geoip2.\+py}}\end{DoxyCompactItemize}
