\doxysection{Référence de la classe pip.\+\_\+internal.\+exceptions.\+Hash\+Error}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError}{}\label{classpip_1_1__internal_1_1exceptions_1_1HashError}\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}


Graphe d\textquotesingle{}héritage de pip.\+\_\+internal.\+exceptions.\+Hash\+Error\+:
% FIG 0


Graphe de collaboration de pip.\+\_\+internal.\+exceptions.\+Hash\+Error\+:
% FIG 1
\doxysubsubsection*{Fonctions membres publiques}
\begin{DoxyCompactItemize}
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a8b1a0890122218544dd1a3e23c416431}{body}} (self)
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a455e73a1648e11e2d124cf5bd30f97f3}{\+\_\+\+\_\+str\+\_\+\+\_\+}} (self)
\end{DoxyCompactItemize}
\doxysubsubsection*{Attributs publics}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_af3c50ea4f7da6636a64b938cda7052c9}{req}}
\end{DoxyCompactItemize}
\doxysubsubsection*{Attributs publics statiques}
\begin{DoxyCompactItemize}
\item 
Optional \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_ad2686ce304abe2499ebe21468dc12057}{req}} = None
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_ad051d7f7e98b51e235a5bc4ca17b302c}{head}} = "{}"{}
\item 
int \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a81cbe1b130a39b1625d11456709e1047}{order}} = -\/1
\end{DoxyCompactItemize}
\doxysubsubsection*{Fonctions membres protégées}
\begin{DoxyCompactItemize}
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a17be3100accef085731b0299b3528866}{\+\_\+requirement\+\_\+name}} (self)
\end{DoxyCompactItemize}


\doxysubsection{Description détaillée}
\begin{DoxyVerb}A failure to verify a package against known-good hashes

:cvar order: An int sorting hash exception classes by difficulty of
    recovery (lower being harder), so the user doesn't bother fretting
    about unpinned packages when he has deeper issues, like VCS
    dependencies, to deal with. Also keeps error reports in a
    deterministic order.
:cvar head: A section heading for display above potentially many
    exceptions of this kind
:ivar req: The InstallRequirement that triggered this error. This is
    pasted on after the exception is instantiated, because it's not
    typically available earlier.\end{DoxyVerb}
 

\doxysubsection{Documentation des fonctions membres}
\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a455e73a1648e11e2d124cf5bd30f97f3}\label{classpip_1_1__internal_1_1exceptions_1_1HashError_a455e73a1648e11e2d124cf5bd30f97f3} 
\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!\_\_str\_\_@{\_\_str\_\_}}
\index{\_\_str\_\_@{\_\_str\_\_}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{\_\_str\_\_()}{\_\_str\_\_()}}
{\footnotesize\ttfamily  str pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+\_\+\+\_\+str\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self }\end{DoxyParamCaption})}

\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a17be3100accef085731b0299b3528866}\label{classpip_1_1__internal_1_1exceptions_1_1HashError_a17be3100accef085731b0299b3528866} 
\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!\_requirement\_name@{\_requirement\_name}}
\index{\_requirement\_name@{\_requirement\_name}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{\_requirement\_name()}{\_requirement\_name()}}
{\footnotesize\ttfamily  str pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+\_\+requirement\+\_\+name (\begin{DoxyParamCaption}\item[{}]{self }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [protected]}}

\begin{DoxyVerb}Return a description of the requirement that triggered me.

This default implementation returns long description of the req, with
line numbers\end{DoxyVerb}
 \Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a8b1a0890122218544dd1a3e23c416431}\label{classpip_1_1__internal_1_1exceptions_1_1HashError_a8b1a0890122218544dd1a3e23c416431} 
\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!body@{body}}
\index{body@{body}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{body()}{body()}}
{\footnotesize\ttfamily  str pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+body (\begin{DoxyParamCaption}\item[{}]{self }\end{DoxyParamCaption})}

\begin{DoxyVerb}Return a summary of me for display under the heading.

This default implementation simply prints a description of the
triggering requirement.

:param req: The InstallRequirement that provoked this error, with
    its link already populated by the resolver's _populate_link().\end{DoxyVerb}
 

Réimplémentée dans \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashMissing_afe037f000b99010da015d0209089d6dd}{pip.\+\_\+internal.\+exceptions.\+Hash\+Missing}}, et \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a24c9ffc7b9a48c74ac53439d56a05dc6}{pip.\+\_\+internal.\+exceptions.\+Hash\+Mismatch}}.



\doxysubsection{Documentation des données membres}
\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_ad051d7f7e98b51e235a5bc4ca17b302c}\label{classpip_1_1__internal_1_1exceptions_1_1HashError_ad051d7f7e98b51e235a5bc4ca17b302c} 
\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!head@{head}}
\index{head@{head}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{head}{head}}
{\footnotesize\ttfamily str pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+head = "{}"{}\hspace{0.3cm}{\ttfamily [static]}}

\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a81cbe1b130a39b1625d11456709e1047}\label{classpip_1_1__internal_1_1exceptions_1_1HashError_a81cbe1b130a39b1625d11456709e1047} 
\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!order@{order}}
\index{order@{order}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{order}{order}}
{\footnotesize\ttfamily int pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+order = -\/1\hspace{0.3cm}{\ttfamily [static]}}

\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_ad2686ce304abe2499ebe21468dc12057}\label{classpip_1_1__internal_1_1exceptions_1_1HashError_ad2686ce304abe2499ebe21468dc12057} 
\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!req@{req}}
\index{req@{req}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{req}{req}\hspace{0.1cm}{\footnotesize\ttfamily [1/2]}}
{\footnotesize\ttfamily Optional pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+req = None\hspace{0.3cm}{\ttfamily [static]}}

\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_af3c50ea4f7da6636a64b938cda7052c9}\label{classpip_1_1__internal_1_1exceptions_1_1HashError_af3c50ea4f7da6636a64b938cda7052c9} 
\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!req@{req}}
\index{req@{req}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{req}{req}\hspace{0.1cm}{\footnotesize\ttfamily [2/2]}}
{\footnotesize\ttfamily pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+req}



La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/pip/\+\_\+internal/\mbox{\hyperlink{pip_2__internal_2exceptions_8py}{exceptions.\+py}}\end{DoxyCompactItemize}
