\doxysection{Référence de la classe pip.\+\_\+internal.\+exceptions.\+Bad\+Command}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1BadCommand}{}\label{classpip_1_1__internal_1_1exceptions_1_1BadCommand}\index{pip.\_internal.exceptions.BadCommand@{pip.\_internal.exceptions.BadCommand}}


Graphe d\textquotesingle{}héritage de pip.\+\_\+internal.\+exceptions.\+Bad\+Command\+:
% FIG 0


Graphe de collaboration de pip.\+\_\+internal.\+exceptions.\+Bad\+Command\+:
% FIG 1


\doxysubsection{Description détaillée}
\begin{DoxyVerb}Raised when virtualenv or a command is not found\end{DoxyVerb}
 

La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/pip/\+\_\+internal/\mbox{\hyperlink{pip_2__internal_2exceptions_8py}{exceptions.\+py}}\end{DoxyCompactItemize}
